<applet code="edu.hawaii.jabsom.tri.ecmo.app.ECMOApp" 
        codebase="http://ecmojo.sourceforge.net/webstart/unpacked"
        archive="browsercode.jar,ecmosim-app-conf.jar,ecmosim-app-scenario.jar,ecmosim-app.jar,jgoodies-forms-1.0.4.jar,jl1.0.jar,mp3spi1.9.2.jar,swingx-0.9.4.jar,tritonus_share.jar"
        width="800" height="600">
  <param name="image" value="applet-loading.gif">
  <param name="boxmessage" value="Loading ECMOjo...">
  <param name="args" VALUE="noargs">      
  <param name="webstart.dir" VALUE=".ECMOjo">      
  <param name="webstart.extra.dir" VALUE="http://ecmojo.sourceforge.net/webstart/extra">      
</applet>