<applet code="@applet.class.main@" 
        codebase="@applet.class.codebase@"
        archive="@applet.class.archive@"
        width="@applet.param.width@" height="@applet.param.height@">
  <param name="image" value="@applet.class.image@">
  <param name="boxmessage" value="@applet.class.boxmessage@">
  <param name="args" VALUE="@applet.class.args@">      
  <param name="webstart.dir" VALUE="@applet.class.webstart.dir@">      
  <param name="webstart.extra.dir" VALUE="@applet.class.webstart.extra.dir@">      
</applet>