<?php

// Database Configuration
$dbms     = 'mysql' ;
$dbhost   = 'mysql4-e' ;
$dbname   = 'e241657_ecmo'   ;
$dbuser   = 'e241657rw' ;
$dbpasswd = 'ecmo' ;

// The mail configuration (for notifications)
$email_full_name = 'ECMOjo';
$email_address   = 'telemed@hawaii.edu';
$smtp_host       = 'mail.hawaii.edu';
$smtp_auth       = true;
$smtp_username   = 'telemed@hawaii.edu';
$smtp_password   = 'east88to';
$smtp_port       = 25;
$mail_sender     = 'smtp';

// Register globals
$PHP_SELF = $_SERVER['PHP_SELF']

?>